websocket:
#  address: wss://ayesha.wiki/ams-erp-ws
  address: ws://attom.nat300.top/ams-erp-ws
logging:
  config: classpath:logback-production.xml

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: 6H3G1PSCARM7QJEXO6VW
  secretKey: 2G7npe8QnUSefIHrhzuHOntCec+aD+i7k22sIGp+
  bucketName: ams-erp

mathServer:
  url: http://127.0.0.1:8037