server:
  port: 8027
  servlet:
      contextPath: /web3d
      session:
        timeout: 1D

spring:
  tomcat:
    test-on-borrow: true
    validation-query: SELECT 1
    validation-interval: 30000
  profiles:
    active: development
  session:
    timeout: 1D
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    'org.springframework.web': DEBUG
    'com.ams': DEBUG
